### ISSUE TITLE
Consider support for Pulsar Manager

### ISSUE THREAD

**Issue by onobc** [spring-projects/spring-pulsar#139]
The Apache [Pulsar Manager](https://github.com/apache/pulsar-manager ) is a web-based GUI management tool for managing and monitoring Pulsar. 

Lets familiarize ourselves with its capabilities and understand how we can incorporate it, make it easier for Spring users to use, etc.. It may be that there is nothing to do here but it is worth looking into.

**Comment by KartikShrivastava** [comment]
Hey @onobc, can I work on this?

**Comment by onobc** [comment]
Hi @KartikShrivastava ,

So PulsarManager is currently in a very outdated state and until it gets up-to-date I would not spend time on this. 

@jonas-grgt has been chipping away at it [here](https://github.com/apache/pulsar-manager/pull/546) and [here](https://github.com/apache/pulsar-manager/pull/548).

**Comment by onobc** [comment]
PulsarManager is quite behind the latest dependency versions which is a big enough hurdle for us to not consider this issue right now. Closing as such, we can re-open later if the opportunity arises.
