### ISSUE TITLE
Re-evaluate PulsarEvent naming / fields

### ISSUE THREAD

**Issue by sobychacko** [spring-projects/spring-pulsar#343]
**[NIT]** I just noticed these event classes (`PulsarEvent`) - nice. I do think `container` is generic term and I am not sure what it is referencing here - I am guessing a listener container? It feels like `PulsarEvent` is really an `PulsarListenerContainerEvent`?  Do you enhancing the description a bit?

_Originally posted by @onobc in https://github.com/spring-projects-experimental/spring-pulsar/pull/342#discussion_r1106578362_

**Comment by onobc** [comment]
Since this is already released out into the wild and no external users are asking for this, going to close and we can revisit when/if needed.
