### ISSUE TITLE
Re-evaluate the use of phase in listener container

### ISSUE THREAD

**Issue by sobychacko** [spring-projects/spring-pulsar#344]
I thought we decided to drop the "phase" support out of the containers as we are not using it currently? Can we nix it out of this one?

_Originally posted by @onobc in https://github.com/spring-projects-experimental/spring-pulsar/pull/342#discussion_r1106584630_

**Comment by onobc** [comment]
This is now used to properly release/acquire resources in a CRaC scenario.
