### ISSUE TITLE
Usage of capturing the listener runnable as a CompletableFuture

### ISSUE THREAD

**Issue by sobychacko** [spring-projects/spring-pulsar#346]
Wdyt about dropping this reference since its not referenced anywhere - the one on the DPMLC is still not referenced either so good bet we do not need the ref.

_Originally posted by @onobc in https://github.com/spring-projects-experimental/spring-pulsar/pull/342#discussion_r1106589801_

**Comment by onobc** [comment]
While we are not using it currently, this future gives us the ability to do something `whenComplete` like possibly log if failure occurs etc. We are not using it currently and that is ok. Closing this accordingly.
