### ISSUE TITLE
Add PulsarServiceConnection support when Spring Boot 3.2.0 is supported

### ISSUE THREAD

**Issue by eddumelendez** [spring-projects/spring-pulsar#384]
In Spring Boot 3.1.0-M2, [Service Connections](https://docs.spring.io/spring-boot/docs/3.1.0-M2/reference/htmlsingle/#howto.testing.testcontainers.service-connections) was introduced.

It would be great to do the same for the project and introduce `PulsarServiceConnection` and set automatically the following properties `spring.pulsar.client.serviceUrl` and `spring.pulsar.administration.service-url`.

At the current state, probably won't be possible unless there is a test module but could be too much. I guess, the proper time would be when merging the autoconfiguration in spring boot support which I hope could be for 3.1.0 release.

**Comment by onobc** [comment]
Thanks for sharing this @eddumelendez ! This is news to me and is very exciting. I look forward to not having to do the `@DynamicPropertySource` every time I use `@Container` in a `@SpringBootTest` just to pass in the server/port info. 

Not sure if it will make it in time for the `3.1.0` - but I did just submit the PR for the merge into SB [here](https://github.com/spring-projects/spring-boot/pull/34763). There will already be too many moving parts to also include the service connection in the initial PR. It would be nice to follow directly after though w/ this support.

**Comment by eddumelendez** [comment]
Thanks for point me to the PR @onobc ! I didn't see that coming 😅

**Comment by onobc** [comment]
Putting this info here to avoid duplication of work in the case where someone sees this issue and decides to implement it as well - I have implemented this (but queued up on the initial SB PR) https://github.com/spring-projects/spring-boot/pull/34763#issuecomment-1564616952

**Comment by onobc** [comment]
Closed via https://github.com/spring-projects/spring-boot/commit/d9af7cec141190fb32e20de6a64c2d3b03b644e4
