### ISSUE TITLE
Add support for virtual threads (Project Loom)

### ISSUE THREAD

**Issue by onobc** [spring-projects/spring-pulsar#414]
This is a Spring wide initiative for the end of the year and Spring Framework has https://github.com/spring-projects/spring-framework/issues/23443 scheduled for the 6.1 release this fall.

- ~[ ] Add support for Java 21 (TODO create issue)~
- ~[ ] Add config prop(s) for enabling virtual threads on listener container executors (default and concurrent)~
- [x] Ensure proper use of synchronized (may not be issue as we only use on initial startup AFAICT)
> ℹ️ The above will likely be turned into individual issues when we start looking into this.

See [this PR](https://github.com/spring-projects/spring-framework/commit/697d5e624761dca1d10cf64738a49ff8ce1b1a0e#diff-aa7b7a0500f5c71aed3b718dae7bd16968e544af2673815305cf844b69f7c95eR109) that adds virtual thread support to Spring Framework for inspiration.

**Comment by wilkinsona** [comment]
> Add config prop(s) for enabling virtual threads on listener container executors (default and concurrent)

What did you have in mind here? A boolean flag to enable virtual threads or to allow an `AsyncTaskExecutor` to be set?FWIW, from what I've seen in other projects the latter is the much more common approach.

**Comment by sobychacko** [comment]
@wilkinsona We can go with the `AsyncTaskExecutor` if other projects are already doing it for virtual threads support. We are already using [AsyncTaskExecutor](https://github.com/spring-projects/spring-pulsar/blob/main/spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java#L108C21-L108C37) for running the listener thread.  What other projects are using it for VT support?

**Comment by wilkinsona** [comment]
You can answer that with a [code search](https://github.com/search?q=org%3Aspring-projects%20AsyncTaskExecutor&type=code).

Anywhere that's using a `SimpleAsyncTaskExecutor` (a new thread per task) is an excellent candidate for using a `VirtualThreadTaskExecutor` when the user's indicated that they want to use virtual threads.

**Comment by onobc** [comment]
Going w/ the `AsyncTaskExecutor` is much simpler than the config prop approach. The containers already support setting the executor. This really becomes an exercise of cleaning up any sync blocks. We will likely want to add a PulsarContainerPropertiesCustomizer in Boot though as the user currently has limited access to what they can configure on the container properties. I will create a code proposal under https://github.com/spring-projects/spring-boot/issues/36347 for this.

**Comment by onobc** [comment]
Closing via 8c415e814b9616fab8d2a4fdef40737d14bd028b
