### ISSUE TITLE
Ability to use non-shaded Pulsar Client with the Spring Boot starter

### ISSUE THREAD

**Issue by jheijmans** [spring-projects/spring-pulsar#431]
Feature request:

The current Pulsar client used by the `spring-pulsar-spring-boot-starter` is a "shaded" jar file, which means all the dependencies are in the same jar and with a modified package name. While shading can be useful to avoid dependency conflicts, it also means users of the jar cannot exclude or override these dependencies through Maven/Gradle. Being able to override dependencies is sometimes desirable/necessary, for example if these dependencies have a known vulnerability. A concrete example: the 2.12.1 version of the client (used by the 0.2 version of the starter contains a vulnerable version of Google Guava.

A non-shaded version of the Pulsar client is available (`pulsar-client-original`), but I cannot use that to override the client used by the starter, as it throws a `ClassNotFoundException` due to the fact the shaded package and the non-shaded packages are different.

Possible solutions would include:
* have the starter use the non-shaded Pulsar Cliente
* give the option of using the non-shaded Pulsar Client (either built-in or with a dependency override)

(PS I could solve the concrete example above, as Pulsar has a 2.12.2 version of the client that does not use the vulnerable Guava version, so I am not looking to solve this particular instance, but more in general.)

**Comment by onobc** [comment]
Hi @jheijmans 

I am glad `2.11.2` solves this particular issue.  I do understand your use case. We will likely always use the shaded version as the default as the client has many dependencies that will clash with user application dependencies. The shading allows the client to use whatever it wants as an internal concern, at the expense of not letting the user manage the dependencies (in your case, exclude a vulnerable lib). 

I believe you could exclude `pulsar-client-all` from the starter and just use the `pulsar-client-orignal` and `pulsar-client-admin-original`.

**Comment by onobc** [comment]
Hi @jheijmans 

Were you able to verify if you could do the suggested workaround from above? 

> I believe you could exclude pulsar-client-all from the starter and just use the pulsar-client-orignal and pulsar-client-admin-original.

**Comment by onobc** [comment]
Closing this out as "wont fix".
