### ISSUE TITLE
Add ability to name listener threads

### ISSUE THREAD

**Issue by onobc** [spring-projects/spring-pulsar#458]
_**NOTE:** Below description directly cloned from https://github.com/spring-projects/spring-kafka/issues/2501_

### Summary
Currently listener thread names are set by the task executor; by default, a `SimpleAsyncTaskExecutor` is used, with thread names

`<beanName>-C-<m>-<n>` where `<beanName>` is usually the listener Id, `<n>` is an incrementing integer, and `<m>` is the index of the child container.

Add an option to supply a thread name, based on the container, with the default returning the container's listenerId. For child containers, this is the parent listener id + `-<m>`.

### Motivation

Project Loom virtual threads have no name by default; making it difficult to correlate container activity in logs, when there are multiple containers.

**Comment by artembilan** [comment]
I see this is not done yet.

Any thought why do we need to do this since there is that `VirtualThreadTaskExecutor` from SF?

Thanks

**Comment by onobc** [comment]
> Any thought why do we need to do this since there is that VirtualThreadTaskExecutor from SF?

Agreed. I was planning on closing this once I verified this is not needed due to `VirtualThreadTaskExecutor`.

**Comment by onobc** [comment]
Closing based on previous comment.

**Comment by artembilan** [comment]
Adding for traceability: https://github.com/spring-projects/spring-boot/issues/36321.

I'm not sure yet what we will decide in Spring Boot, but having a hook for setting a custom `VirtualThreadTaskExecutor` with desired thread name prefix should be enough as it always was from existing API.
