### ISSUE TITLE
Setting subscription name using `spring.pulsar.consumer.subscription.type` configuration property doesn't work

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-pulsar#488]
This is a very similar issue to #480.

Subscription property type set using `spring.pulsar.consumer.subscription.type` doesn't get applied when creating consumer due to the following:

1. `PulsarContainerProperties` contains a default value for `subscriptionType`:
https://github.com/spring-projects/spring-pulsar/blob/015346d095dadbba937f961c6eb75bd2cbbd1446/spring-pulsar/src/main/java/org/springframework/pulsar/listener/PulsarContainerProperties.java#L61
https://github.com/spring-projects/spring-pulsar/blob/015346d095dadbba937f961c6eb75bd2cbbd1446/spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java#L324-L328
2. Subscription type value set using `spring.pulsar.consumer.subscription.type` gets applied here:
https://github.com/spring-projects/spring-pulsar/blob/015346d095dadbba937f961c6eb75bd2cbbd1446/spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarConsumerFactory.java#L80-L82
3. However, it gets overwritten few lines below when values from step 1. are applied: 
 https://github.com/spring-projects/spring-pulsar/blob/015346d095dadbba937f961c6eb75bd2cbbd1446/spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarConsumerFactory.java#L92-L94

**Comment by onobc** [comment]
What it boils down to is who is the final arbiter of default values, the `@PulsarListener` or the `spring.pulsar.consumer.*` config properties. Currently, the annotation props get precedence. 

A few options:

* We could have a property on the annotation that indicates which defaults should apply
* We could null out the defaults on the annotations (lets the underlying system decide the defaults, not the annotations)
* We could leave it as-is and force configuration for listeners to be done through the annotation

**Comment by onobc** [comment]
@vpavic after looking into this further the reasonable thing to do is drop the defaults from the annotations and only set those fields when/if the user specifies them on the annotation. This is in line w/ what Spring for Apache Kafka  does w/`@KafkaListener`. I will do that now and we can decide what to do w/ the #483 after we see this new PR.

**Comment by onobc** [comment]
### Use config props
To use the `spring.pulsar.consumer.subscription-type` on `@PulsarListener` set the `subscriptionType` attribute to `{}` as follows:

```java
@PulsarListener(topics = "my-topic", subscriptionType = {})
void listen(String msg) {
	...
}
```

### Use customizer
Another option is to use a customizer as shown below. Also note that when there is only a single listener and a single customizer that it will be automatically applied:

```java
@PulsarListener(topics = "my-topic")
void listen(String msg) {
	...
}

@Bean
PulsarListenerConsumerBuilderCustomizer<String> myCustomizer() {
	return (builder) -> builder.subscriptionType(SubscriptionType.Failover);
}

```

**Comment by onobc** [comment]
Closing via https://github.com/spring-projects/spring-pulsar/commit/836d385d8696f28f1229ade22efd3fa6adf15720
