### ISSUE TITLE
Removed checked exceptions from framework APIs

### ISSUE THREAD

**Issue by onobc** [spring-projects/spring-pulsar#547]
As pointed out by @jonasgeiregat in https://github.com/spring-projects/spring-pulsar/discussions/546, the checked exception on `PulsarTemplate.send*` is not consistent w/ other Spring templates and forces users to catch `PulsarClientException` always. 

Let's instead return a runtime variant of `PulsarClientException`.

**Comment by jonasgeiregat** [comment]
Was also considering to remove `PulsarClientException` from `PulsarProducerFactory` as it had the same inconvenient effect.
