### ISSUE TITLE
Pull topic-resolution.adoc up a level in docs

### ISSUE THREAD

**Issue by onobc** [spring-projects/spring-pulsar#644]
The topic-resolution.adoc can be pulled up to the same level as the imperative and reactive reference as it is identical and used by both of them. Original motivation below:

cc: @KartikShrivastava 

> Hey @onobc, I got a question while making this change:
> 
> * I noticed that `Topic Resolution` present in `reactive-pulsar.adoc` is same as that of imperative, so why did we add it as a separate sub-section? I've replicated the similar behaviour(by creating a separate section for it), but imho we can directly link the imperative `Topic Resolution` to avoid confusion

_Originally posted by @onobc in https://github.com/spring-projects/spring-pulsar/issues/631#issuecomment-2054150562_

**Comment by KartikShrivastava** [comment]
update: Created [PR](https://github.com/spring-projects/spring-pulsar/pull/663) to fix this
