### ISSUE TITLE
Fix documentation for Spring Boot starters

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-pulsar#662]
Looks like an auto-configuration for Spring for Apache Pulsar is now a part of Spring Boot project: https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#messaging.pulsar.

So, documentation has to be fixed respectively. For now it still talks about `spring-pulsar-spring-boot-starter`: https://docs.spring.io/spring-pulsar/docs/1.1.0-RC1/reference/reference/pulsar.html.

Also, I don't think it still make sense to mention the old version of the project in the docs since we already in version `1.1.x`: https://docs.spring.io/spring-pulsar/docs/1.1.0-RC1/reference/reference/pulsar/quick-tour.html#_dependencies

**Comment by onobc** [comment]
Great catch @artembilan. Agreed on the removing the old version. Will get this in before GA.

**Comment by artembilan** [comment]
Apparently same goes for the `spring-boot-starter-pulsar-reactive`, where we mention an old one yet - `spring-pulsar-reactive-spring-boot-starter`: https://docs.spring.io/spring-pulsar/docs/1.1.0-RC1/reference/reference/reactive-pulsar.html#_preface
