### ISSUE TITLE
Explore options to reduce boilerplate code in config props

### ISSUE THREAD

**Issue by onobc** [spring-projects/spring-pulsar#73]
1. Can we use Java Record for config props now? 
2. What are our thoughts about Lombok.

This is just an improvement ticket.

**Comment by alpreu** [comment]
Looks like using Java records is supported now: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#records-and-configurationproperties

The only thing I dislike is that we would have to put a lot of fields into the constructor if I understand it correctly

**Comment by onobc** [comment]
Oh that is great news @alpreu . 

I am ok w/ having to add the fields in the `<init>` as we need to doc them so that the doc gen stuff works. (IOW - we would have to do that somewhere anyways). I think getting rid of the get/set would be a huge improvement.

**Comment by onobc** [comment]
**Suggestion** Let's pause this for now. Once SB supports descriptions on the record fields, we will continue.

**Comment by onobc** [comment]
The config props have moved into Spring Boot proper and any improvements or modification will be handled there on a user requested/needed basis.
