### ISSUE TITLE
Spring property place holder for topics not working in PulsarListener annotation

### ISSUE THREAD

**Issue by alikelleci** [spring-projects/spring-pulsar#752]
When using @PulsarListener we can specify the topics by using property placeholders or SpEL expressions.
Using SpEL expressions do work, but propery placeholders do not work: 

`@PulsarListener(topics = "${app.topics.foo}")`

**Comment by alikelleci** [comment]
works with latest version

**Comment by onobc** [comment]
Hi @alikelleci - did you end up getting it working?

**Comment by alikelleci** [comment]
@onobc sorry for the late reply, i was off for a while. Yes i got it working.
