### ISSUE TITLE
add support for an embedded pulsar instance (e.g. @EmbeddedPulsar)

### ISSUE THREAD

**Issue by zyro23** [spring-projects/spring-pulsar#813]
it would be great to be able to use an embedded pulsar instance for testing (and local development), as an alternative to an external pulsar instance/(test-)container.

i am thinking of sth. like `@EmbeddedPulsar`/`EmbeddedPulsarBroker`, similar to spring-kafka's [`@EmbeddedKafka`](https://github.com/spring-projects/spring-kafka/blob/v3.2.3/spring-kafka-test/src/main/java/org/springframework/kafka/test/context/EmbeddedKafka.java)/[`EmbeddedKafkaBroker`](https://github.com/spring-projects/spring-kafka/blob/v3.2.3/spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java) (ref. https://docs.spring.io/spring-kafka/reference/testing.html#embedded-kafka-annotation).

i think pulsar already ships the needed infra with [`PulsarStandalone`](https://github.com/apache/pulsar/blob/v3.3.1/pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandalone.java) and [`PulsarStandaloneBuilder`](https://github.com/apache/pulsar/blob/v3.3.1/pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandaloneBuilder.java).

thank you!

**Comment by jonas-grgt** [comment]
Essentially an embedded or a testcontainer based pulsar would spin-up an actual pulsar cluster.
Spring-boot offers good support for testcontainers then, what would be so great about also having a embedded pulsar?

**Comment by zyro23** [comment]
i see it as kind of an in-between of mocking and a real instance that allows testing using the actual stack but without the need to run accompanying containers or an external service.

like databases, mail-servers, file-servers, etc. that are available in embedded form as well as in form of (test-)containers - being able to mix & match is a plus, imho.

regarding functionality, having the embedded broker instance available in the test context means - theoretically - that you can make test assertions against the state of the broker.

depending on the ci-environment, it can make things simpler if only a jvm is required to run, as it is not always easily possible to run multiple/additional containers in test pipelines.

anyway, feel free to rate this "nice-to-have" instead of "would-be-great".

**Comment by onobc** [comment]
Hi @zyro23 , it is very unlikely that an embedded pulsar will be added as it ends up being a big burden to maintain and keep up. If Testcontainers would have been available at the time then EmbeddedKafka would most likely not have been added to Spring Kafka. Another downside of the embedded approach is that while it approaches the real container, it is not the real container and there are chances bugs get by. 

As @jonas-grgt pointed out, the SB support for TC is really solid. You can also arrange tests such that they can share the same container and not have to start up multiple times. Here is an [example IT](https://github.com/spring-projects/spring-pulsar/blob/ca192c673e4d08064f643935861de12bbc6e92f2/integration-tests/src/intTest/java/org/springframework/pulsar/inttest/config/DefaultTenantAndNamespaceTests.java#L45) where we use `@Nested` `@SpringBootTest` w/ SB `@ServiceConnection` to handle the startup etc..

I do understand your points above and the flexibility the embedded server brings. It ultimately comes down to the burden of maintaining it.

**Comment by zyro23** [comment]
trade-off understood. thanks for consideration/feedback.

**Comment by onobc** [comment]
> trade-off understood. thanks for consideration/feedback.

Thank you @zyro23 for submitting the issue and the great discussion.
