### ISSUE TITLE
Non-shaded protobuf-java causing class mismatch issues

### ISSUE THREAD

**Issue by onobc** [spring-projects/spring-pulsar#876]
The Pulsar client lib does not shade `com.google.protobuf:protobuf-java` and it is causing user's problems as described in original post by @nandorholozsnyak in https://github.com/spring-projects/spring-pulsar/issues/114#issuecomment-2399976242_
            
### Workaround 1
Upgrade to Pulsar client `3.3.2` as he `protobuf-java` has been updated to `3.25.5`.

If you plan on updating to the upcoming spring-pulsar `1.2.0-RC1 `release (Spring Boot `3.4.0-RC1` / week of Oct 18) you will get this update automatically.
If you don't plan on updating Spring Pulsar then, you can  override the version of Pulsar as described [here](https://docs.spring.io/spring-pulsar/docs/1.2.0-M2/reference/appendix/override-boot-dependencies.html).

This will bring the `protobuf-java` up to a recent version, solving the original author's issue, but will not fix future version mismatches.

### Workaround 2
You can exclude `protobuf-java` from the current `pulsar-client-all `and provide the more recent dependency ([example here](https://docs.spring.io/spring-pulsar/docs/1.2.0-M2/reference/appendix/override-boot-dependencies.html).
Something like:
```
api ("org.apache.pulsar:pulsar-client-all") {
	exclude group: 'com.google.protobuf:protobuf-java'
}
api "com.google.protobuf:protobuf-java:3.25.5"
```

### Improvement 1
We already exclude some other unwanted dependencies from the Pulsar lib ([here](https://github.com/spring-projects/spring-pulsar/blob/e137049fda35b0182e27471334f653fe5b563b3f/spring-pulsar/spring-pulsar.gradle#L10-L14).
We should likely exclude `protobuf-java` as well as we do include it explicitly already as optional dependency ([here](https://github.com/spring-projects/spring-pulsar/blob/e137049fda35b0182e27471334f653fe5b563b3f/spring-pulsar/spring-pulsar.gradle#L26).

We will try to get the above improvement into the upcoming `1.2.0-RC1 `release as well.

### Improvement 2
We should also see about shading the protobuf-java lib in the Pulsar client libs to avoid this downstream required massaging.

**Comment by nandorholozsnyak** [comment]
Hello @onobc 
Thank you for the issue here too, just a quick question for clarity: `The Pulsar client lib does not shade com.google.protobuf:protobuf-java and it is causing user's problems as described in original post`
Indeed the pulsar-client lib is not shading it, but is it the real issue? If it would it may break others as well isnt it?

**Comment by onobc** [comment]
Hi @nandorholozsnyak 

> pulsar-client lib is not shading it, but is it the real issue? If it would it may break others as well isnt it?
> Indeed the pulsar-client lib is not shading it, but is it the real issue? 

If one were to pull `spring-pulsar` out of the equation and consume the `pulsar-client` lib directly, they would transitively consume the older version of `protobuf-java` which could cause problems.

**Comment by nandorholozsnyak** [comment]
Hi @onobc 
Thank you so much for the info.

**Comment by onobc** [comment]
Looks like this may get fixed in Pulsar proper as well: https://github.com/apache/pulsar/pull/23468

**Comment by nandorholozsnyak** [comment]
Hehe, it is happening :D What a coincidence.
